In [18]:
import numpy as np

In [19]:
# 34
np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [20]:
# 35
a = np.ones(5) * 2
b = np.ones(5) * 3
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)
a

array([-5., -5., -5., -5., -5.])

In [21]:
# 36
a = np.random.uniform(0,100,5)
print(a)
print(a//1) # 따지자면 버림
print(a.astype(int)) # 따지자면 버림
print(np.round(a,0)) # 반올림
print(np.trunc(a)) # 버림
print(np.ceil(a)) # 올림
print(np.floor(a)) # 버림

[50.14218905 49.43273796 16.10421357 73.41202516 49.9618156 ]
[50. 49. 16. 73. 49.]
[50 49 16 73 49]
[50. 49. 16. 73. 50.]
[50. 49. 16. 73. 49.]
[51. 50. 17. 74. 50.]
[50. 49. 16. 73. 49.]


In [22]:
# 37
a = np.zeros([5,5])
a += np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [23]:
# 38
def array_maker():
    num = np.random.randint(0,20,10)
    return np.array(num)
array_maker()

array([ 7, 16,  2,  1, 14,  5, 11, 12,  5, 13])

In [24]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [25]:
# 39
np.linspace(0,1,11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [26]:
# 40
a = np.random.randint(0,20,10)
a.sort()
a

array([ 2,  5,  7,  8,  8, 11, 12, 13, 18, 18])

In [27]:
# 41
a = np.random.randint(0,20,5)
np.add.reduce(a)

39

In [28]:
# 42
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
print(a==b)
equal = np.allclose(a,b)
print(equal)
equal = np.array_equal(a,b)
print(equal)

[False  True False  True False]
False
False


In [29]:
# 43
a = np.ones(10)
a.flags.writeable = False

In [30]:
# 44
a = np.random.randint(0,50,2)
print(a)
x, y = a[0], a[1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[32  3]
32.14031735997639
0.09347678115858947


In [31]:
# 45
a = np.random.randint(0,20,5)
a[np.argmax(a)] = 0
a

array([ 8,  0, 15,  9,  3])

In [32]:
# 46
a = np.ones([5,5], [('x', float), ('y', float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
a

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

In [33]:
# 47
a = np.random.randint(0,20,3)
b = np.random.randint(0,20,4)
c = np.ones([len(a), len(b)])
for i in range(len(a)):
    for j in range(len(b)):
        c[i][j] = 1 / (a[i] - b[j])
c

C:\Users\gotze\AppData\Local\Temp\ipykernel_24340\59207808.py:7: RuntimeWarning: divide by zero encountered in long_scalars
  c[i][j] = 1 / (a[i] - b[j])


array([[ 0.5       , -0.125     , -0.07142857, -0.14285714],
       [        inf, -0.1       , -0.0625    , -0.11111111],
       [ 0.16666667, -0.25      , -0.1       , -0.33333333]])

In [34]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [35]:
# 48
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [36]:
# 49
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [37]:
# 50
a = np.arange(100)
n = np.random.uniform(0,100)
index = (np.abs(a-n)).argmin()
print(n, a[index])

43.2583398926757 43


In [38]:
# 51
a = np.zeros(10, [('position', [('x', float, 1), ('y', float, 1)]), ('color', [('r', float, 1), ('g', float, 1), ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\gotze\AppData\Local\Temp\ipykernel_24340\349660227.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(10, [('position', [('x', float, 1), ('y', float, 1)]), ('color', [('r', float, 1), ('g', float, 1), ('b', float, 1)])])


In [39]:
# 52
a = np.random.random((10,2))
x, y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.20837851 0.13296744 0.66376026 0.63777108 0.53052986
  0.49815972 0.26372052 0.6527101  0.59424443]
 [0.20837851 0.         0.16500545 0.73746267 0.55659742 0.70795243
  0.70435157 0.3755141  0.71830915 0.57300607]
 [0.13296744 0.16500545 0.         0.78612421 0.69545454 0.65976646
  0.57237782 0.2109518  0.77278852 0.68148879]
 [0.66376026 0.73746267 0.78612421 0.         0.49208987 0.43083008
  0.81158824 0.90625106 0.03237863 0.31673357]
 [0.63777108 0.55659742 0.69545454 0.49208987 0.         0.79149117
  1.03835713 0.89320821 0.45978411 0.17567452]
 [0.53052986 0.70795243 0.65976646 0.43083008 0.79149117 0.
  0.41129906 0.67627072 0.44867184 0.63821829]
 [0.49815972 0.70435157 0.57237782 0.81158824 1.03835713 0.41129906
  0.         0.45611119 0.82139544 0.92719591]
 [0.26372052 0.3755141  0.2109518  0.90625106 0.89320821 0.67627072
  0.45611119 0.         0.89918281 0.85792446]
 [0.6527101  0.71830915 0.77278852 0.03237863 0.45978411 0.44867184
  0.82139544 0.89918

In [40]:
# 53
a = (np.random.rand(10)*100).astype(np.float32)
print(a)
a = a.astype(np.int32)
print(a)

[57.581646  28.047138  97.78651   13.846349  14.424364  38.67317
  6.6994505 45.928967  32.48169   33.820324 ]
[57 28 97 13 14 38  6 45 32 33]


In [41]:
# 54
from io import StringIO
a = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
b = np.genfromtxt(a, delimiter=",", dtype=np.int)
print(b)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\gotze\AppData\Local\Temp\ipykernel_24340\3699910187.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b = np.genfromtxt(a, delimiter=",", dtype=np.int)


In [42]:
# 55
a = np.arange(16).reshape(4,4)
for index, value in np.ndenumerate(a):
    print(index, value)
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15
(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15


In [43]:
# 56
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [44]:
# 57
a = np.ones(10)
n = 3
index = np.random.randint(0,len(a), 1)
a[index] = n
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 3.])

In [45]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [46]:
# 58
a = np.random.rand(3,4) * 10
print(a)
for i in range(len(a)):
    mean = np.mean(a[i])
    print(mean)
    for j in range(len(a[0])):
        a[i,j] -= mean
print(a)

[[3.16060745 2.53730894 8.28296468 6.80483254]
 [3.06622218 0.30952914 5.54754003 5.70058012]
 [9.27224967 6.58351223 4.23925001 3.57251331]]
5.196428400696751
3.6559678702851155
5.916881305369084
[[-2.03582095 -2.65911946  3.08653628  1.60840414]
 [-0.58974569 -3.34643873  1.89157216  2.04461225]
 [ 3.35536836  0.66663093 -1.6776313  -2.344368  ]]


In [47]:
X = np.random.rand(3, 4)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.1233343   0.29901154  0.20414511 -0.37982234]
 [ 0.22481428  0.0086011  -0.03458983 -0.19882555]
 [ 0.1131221   0.5011516  -0.27950789 -0.3347658 ]]


In [48]:
# 59
a = np.random.randint(0,10,(6,4))
print(a)
print(a[a[:,1].argsort()])

[[7 5 2 1]
 [7 1 0 7]
 [3 7 5 8]
 [1 2 3 4]
 [1 8 6 2]
 [2 0 2 3]]
[[2 0 2 3]
 [7 1 0 7]
 [1 2 3 4]
 [7 5 2 1]
 [3 7 5 8]
 [1 8 6 2]]


In [49]:
# 60
a = np.random.randint(0,3,(3,10))
print((~a.any(axis=0)).any())

a=np.array([[0,1,np.nan], [1,2,np.nan], [4,5,np.nan]])
print(np.isnan(a).all(axis=0))

False
[False False  True]


In [50]:
# 61
a = np.random.uniform(0,10,50)
n = 7
m = a[np.abs(a - n).argmin()]
print(m)

7.091038753027572


In [51]:
# 62
a = np.arange(4).reshape(4,1)
b = np.arange(4).reshape(1,4)
it = np.nditer([a,b,None])
for x,y,z in it:
    z[...] = x + y
print(it.operands[2])

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [52]:
# 63
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

a = NamedArray(np.arange(10), "range_10")
print (a.name)

range_10
