In [1]:
# 1
import numpy as np

In [2]:
# 2
np.__version__

'1.21.5'

In [3]:
# 3
arr = np.zeros(10)
# arr = np.full(10,0)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# 4
# arr.size, arr.shape, type(arr) 오답
arr = np.zeros(10)
print(arr.itemsize * arr.size)
arr = np.full(10,0)
print(arr.itemsize * arr.size)
print(arr.nbytes)

80
40
40


In [ ]:
# 5
# %run `python -c "import numpy; numpy.info(numpy.add)"`

In [7]:
# 6
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
# 7
# arr = np.array(range(10, 50))
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
# 8
arr = np.array(range(10, 50))
arr = arr[::-1]
arr

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [8]:
# 9
arr = np.array(range(9)).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
# 10
arr = np.array([1,2,0,0,4,0])
i = np.nonzero(arr)
i

(array([0, 1, 4], dtype=int64),)

In [10]:
# 11
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# 12
arr = np.random.random([3,3,3])
arr

array([[[0.64197272, 0.43467412, 0.33998771],
        [0.12725869, 0.32156701, 0.46707423],
        [0.28282453, 0.91164096, 0.57206283]],

       [[0.06504472, 0.71204753, 0.30849221],
        [0.84781027, 0.60134874, 0.52953014],
        [0.55867248, 0.74671478, 0.61484619]],

       [[0.68901955, 0.11457419, 0.14632812],
        [0.76816248, 0.0285821 , 0.96171145],
        [0.5651574 , 0.88641728, 0.57623853]]])

In [12]:
# 13
arr = np.random.random([10,10])
max = arr.max()
min = arr.min()
max, min

(0.994688136912083, 0.03084725082728701)

In [13]:
# 14
arr = np.random.random(30)
mean = arr.mean()
mean

0.5268138482633562

In [14]:
# 15
arr = np.ones([5,6])
# arr[1:-1][1:-1] = 0 -> 위아래 행 제외 후, 나머지 행에 대해 열 추출
arr[1:-1,1:-1] = 0 # 행, 열에 대해 동시에 접근
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
# 16
arr = np.ones([3,3])
arr = np.pad(arr, pad_width=1, constant_values=5)
arr

array([[5., 5., 5., 5., 5.],
       [5., 1., 1., 1., 5.],
       [5., 1., 1., 1., 5.],
       [5., 1., 1., 1., 5.],
       [5., 5., 5., 5., 5.]])

In [8]:
# 17
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [17]:
# 18
arr = np.diag(np.arange(4)+1, k=-1) # 대각선 주기, 대각선 위치
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [18]:
# 19
# arr = np.zeros(64).reshape([8,8])
arr = np.zeros([8,8])
arr[1:2, 1::2] = 1
arr[0::2, 0::2] = 1
arr

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
# 20
arr = np.arange(6*7*8).reshape([6,7,8])
np.unravel_index(99,[6,7,8]) # 100은 두번째 x, 여섯번째 y, 4번째 z에 있음

(1, 5, 3)

In [20]:
# 21
arr = np.array([[0,1],[1,0]])
arr = np.tile(arr, [4,4])
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [21]:
# 22
arr = np.random.random([5,5])
arr = (arr-arr.mean()) / arr.std()
arr

array([[ 1.22231838,  1.44326548,  0.04084011,  0.2514073 ,  0.79924341],
       [ 0.47037193, -0.63746005,  0.33753961, -1.73457233,  1.14274824],
       [-0.55090154,  1.44917307, -1.129875  ,  0.83091438,  0.67205795],
       [-0.29080258, -0.86217688, -1.74425515, -0.50975309,  0.18909015],
       [ 0.02263684, -2.11452671,  0.30372154,  1.20728904, -0.80829408]])

In [22]:
# 23
color = np.dtype([('r', np.ubyte), ('g', np.ubyte), ('b', np.ubyte), ('a', np.ubyte)])

In [23]:
# 24
a = np.ones([5,3])
b = np.ones([3,2])
c= np.dot(a,b)
c

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [24]:
# 25
a = np.arange(15)
filter = (a>=3) & (a<=8)
a[filter] *= -1
a

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14])

In [25]:
# 26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [26]:
# 27
z = np.arange(5)
print(z)
print(z**z)
print(2 << z >> 2)
print(z <- z)
print(1j*z)
print(z/1/1)
# print(z<z>z)

[0 1 2 3 4]
[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


In [27]:
# 28
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\gotze\AppData\Local\Temp\ipykernel_19052\3505345307.py:2: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\gotze\AppData\Local\Temp\ipykernel_19052\3505345307.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [28]:
# 29
z = np.random.uniform(-10,10,5)
print(np.ceil(np.abs(z)), z)
print(np.copysign(np.ceil(np.abs(z)), z))

[7. 5. 4. 6. 4.] [-6.245711   -4.38738853  3.08621439  5.30684972  3.25941082]
[-7. -5.  4.  6.  4.]


In [29]:
# 30
a = np.random.randint(0,20,100)
b = np.random.randint(0,20,100)
c = np.intersect1d(a,b)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
# 31
with np.errstate(all='ignore'):
    np.arange(1) / 0

In [31]:
# 32
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\gotze\AppData\Local\Temp\ipykernel_19052\2920205242.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [32]:
# 33
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)

yesterday, today, tomorrow

(numpy.datetime64('2023-01-10'),
 numpy.datetime64('2023-01-11'),
 numpy.datetime64('2023-01-12'))